import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = resolve(__dirname, '..', 'package.json');
const outPath = resolve(__dirname, '..', 'src', 'environments', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
const { version, name } = pkg;
const buildTime = new Date().toISOString();

const content = `// ─── Auto-generated by prebuild — do not edit manually
export const APP_VERSION = '${version}';
export const APP_BUILD = '${buildTime}';
`;

writeFileSync(outPath, content, 'utf-8');
console.log(`✅  Version ${version} written to src/environments/version.ts  (${buildTime})`);
